### ISSUE TITLE
Create the next stable tag from main

### ISSUE THREAD

**Issue by tdiesler** [sicpa-dlab/peer-did-jvm#36]
## What

Please create a tag (i.e. v0.4.0) for recent changes to main

## Why

[nessus-didcomm](https://github.com/tdiesler/nessus-didcomm) likes to integrate with [Apache Camel](https://camel.apache.org/), which cannot have transitive dependencies on SNAPSHOTS

Please also consider publishing that tag to maven central. Camel might reject the DidComm component if it comes with repositories other than central

**Comment by dkulic** [comment]
Closing this, because version 0.4.0 is released
